name: Build Patched Sukisu-Ultra Manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SukiSU-Ultra
        run: git clone --depth 1 https://github.com/SukiSU-Ultra/SukiSU-Ultra.git .

      - name: Bypass Mismatch Check
        run: |
          sed -i 's/fun checkUAPIMismatch(): Boolean {/fun checkUAPIMismatch(): Boolean { return false/g' manager/app/src/main/java/com/sukisu/ultra/Natives.kt
          sed -i 's/val showVersionMismatchWarning: Boolean/val showVersionMismatchWarning: Boolean = false \/\//g' manager/app/src/main/java/com/sukisu/ultra/ui/screen/home/HomeUiState.kt

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK
        working-directory: manager
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-Ultra-Patched
          path: manager/app/build/outputs/apk/**/*.apk
